// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0x1o4lUJvF0HiJAeGxAmBIcGxyZd9YH0',
    appId: '1:216937294504:web:e9274d308eb92a074a309d',
    messagingSenderId: '216937294504',
    projectId: 'ride-together-f2720',
    authDomain: 'ride-together-f2720.firebaseapp.com',
    storageBucket: 'ride-together-f2720.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_6tXNO-2ApKU4lfNGWA4SdH-D4nUO4Xc',
    appId: '1:216937294504:android:bd9b116e3f2cfd074a309d',
    messagingSenderId: '216937294504',
    projectId: 'ride-together-f2720',
    storageBucket: 'ride-together-f2720.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjq21WsAPDqb4yYIe6XyHu1y4EckMRNN0',
    appId: '1:216937294504:ios:70d3eece73a4f4c94a309d',
    messagingSenderId: '216937294504',
    projectId: 'ride-together-f2720',
    storageBucket: 'ride-together-f2720.firebasestorage.app',
    iosClientId: '216937294504-jbigf29nnt26jqtj9eovf7vjvflm99f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjq21WsAPDqb4yYIe6XyHu1y4EckMRNN0',
    appId: '1:216937294504:ios:70d3eece73a4f4c94a309d',
    messagingSenderId: '216937294504',
    projectId: 'ride-together-f2720',
    storageBucket: 'ride-together-f2720.firebasestorage.app',
    iosClientId: '216937294504-jbigf29nnt26jqtj9eovf7vjvflm99f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideTogether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0x1o4lUJvF0HiJAeGxAmBIcGxyZd9YH0',
    appId: '1:216937294504:web:9e657f002df9f32e4a309d',
    messagingSenderId: '216937294504',
    projectId: 'ride-together-f2720',
    authDomain: 'ride-together-f2720.firebaseapp.com',
    storageBucket: 'ride-together-f2720.firebasestorage.app',
  );
}
